#pragma once
#define LINK0_PULSE_PIN 12
#define LINK0_DIR_PIN 13
#define LINK1_PULSE_PIN 27
#define LINK1_DIR_PIN 14
#define LINK2_PULSE_PIN 25
#define LINK2_DIR_PIN 26
#define LINK3_PULSE_PIN 33
#define LINK3_DIR_PIN 32

#define PULSE_PINS {LINK0_PULSE_PIN, LINK1_PULSE_PIN, LINK2_PULSE_PIN, LINK3_PULSE_PIN}
#define DIR_PINS {LINK0_DIR_PIN, LINK1_DIR_PIN, LINK2_DIR_PIN, LINK3_DIR_PIN}

#define LINK0_SWITCH_PIN 2
#define LINK1_SWITCH_PIN 4
#define LINK2_SWITCH_PIN 5
#define LINK3_SWITCH_PIN 18